Update 'save' and 'load' commands in User Guide
AY2425S1-CS2103T-T12-4/tp pull request #127
Opened 2024-10-22 09:51 UTC by ChenLeiyu

fixes #126

2024-10-23 13:05 UTC, JJtan2002 requested changes
Please make the changes as needed according to my comments, thank you Lei Yu.

2024-10-23 13:05 UTC, JJtan2002 commented on docs/UserGuide.md
> +# GamerBook PRO MAX User Guide
Should be GamerBook Pro Max, without the full capitalisation.

2024-10-23 13:21 UTC, ChenLeiyu commented on docs/UserGuide.md
> +# GamerBook PRO MAX User Guide
Done, thank you for the review.

2024-10-24 02:48 UTC, JJtan2002 approved these changes
LGTM!

2024-10-24 02:48 UTC, merged